repos:
  - repo: builtin
    hooks:
      - id: check-toml
        groups: [lint]
      - id: check-yaml
        groups: [lint]
      - id: check-merge-conflict
        groups: [lint]
      - id: end-of-file-fixer
        groups: [format]
      - id: mixed-line-ending
        args: [--fix=lf]
        groups: [format]
      - id: trailing-whitespace
        groups: [format]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff-check
        types_or: [python, pyi, pyproject]
        args: [--fix]
        groups: [lint]
      - id: ruff-format
        types_or: [python, pyi, markdown]
        groups: [format]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.0
    hooks:
      - id: mypy
        args: []
        pass_filenames: false
        additional_dependencies: ["orjson>=3.9"]
        groups: [lint]
